# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)



platform :android do

  lane :distribute do

    gradle(
  task: "assembleDebug",
  properties: {
    "android.injected.signing.store.file" => "../debug.keystore",
    "android.injected.signing.store.password" => "android",
    "android.injected.signing.key.alias" => "androiddebugkey",
    "android.injected.signing.key.password" => "android"
  }
)

    

    firebase_app_distribution(

        app: "1:330382477506:android:dd3c205a778c5ffa7c535b",

        groups: "dodo-app-tester",

        # ENV["FIREBASE_TOKEN"]은 GitHub Secrets에서 자동으로 가져올 거야

        firebase_cli_token: ENV["FIREBASE_TOKEN"]

    )

  end

end
