name: Android CI/CD

on:
  push:
    branches: [ "main", "feat/29/ui" ]

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> local.properties
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> local.properties
          echo "WEB_URL=${{ secrets.WEB_URL }}" >> local.properties

      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.3'
          bundler-cache: true

      - name: Install Fastlane Plugins
        run: bundle exec fastlane install_plugins

      - name: Decode Keystore
        run: echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > debug.keystore

      - name: Build and Distribute
        run: bundle exec fastlane distribute
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
          WEB_URL: ${{ secrets.WEB_URL }}